[package]
name = "ooo"
version = "0.0.2"
edition = "2021"
license = "MIT"
description = "The more operators for Rust. Such us 'Increase' and 'Decrease'."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level = 3
